/* eslint-disable max-lines */
const roomsQueryAllKeys = {
	input: {
		WHERE: {
			AND: [
				{
					IS: {
						rooms_furniture: "*Tables*"
					}
				},

				{
					GT: {
						rooms_seats: 300
					}
				}
			]
		},

		OPTIONS: {
			COLUMNS: ["rooms_fullname", "rooms_shortname",
				"rooms_furniture", "rooms_number", "rooms_name", "rooms_address",
				"rooms_type", "rooms_furniture", "rooms_href", "rooms_seats", "rooms_lat", "rooms_lon"],
			ORDER: {dir: "DOWN",
				keys: ["rooms_shortname"]}
		}
	},

	output:
		[{rooms_fullname:"Robert F. Osborne Centre",
			rooms_shortname:"OSBO",
			rooms_furniture:"Classroom-Movable Tables & Chairs",
			rooms_number:"A",
			rooms_name:"OSBO_A",
			rooms_address:"6108 Thunderbird Boulevard",
			rooms_type:"Open Design General Purpose",
			rooms_href:"http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/OSBO-A",
			rooms_seats:442,
			rooms_lat:49.26047,
			rooms_lon:-123.24467},
		{rooms_fullname:"Life Sciences Centre",
			rooms_shortname:"LSC",
			rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",
			rooms_number:"1001",
			rooms_name:"LSC_1001",
			rooms_address:"2350 Health Sciences Mall",
			rooms_type:"Tiered Large Group",
			rooms_href:"http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/LSC-1001",
			rooms_seats:350,
			rooms_lat:49.26236,
			rooms_lon:-123.24494},
		{rooms_fullname:"Life Sciences Centre",
			rooms_shortname:"LSC",
			rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",
			rooms_number:"1002",
			rooms_name:"LSC_1002",
			rooms_address:"2350 Health Sciences Mall",
			rooms_type:"Tiered Large Group",
			rooms_href:"http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/LSC-1002",
			rooms_seats:350,
			rooms_lat:49.26236,
			rooms_lon:-123.24494},
		{rooms_fullname:"Hebb",
			rooms_shortname:"HEBB",
			rooms_furniture:"Classroom-Fixed Tables/Fixed Chairs",
			rooms_number:"100",
			rooms_name:"HEBB_100",
			rooms_address:"2045 East Mall",
			rooms_type:"Tiered Large Group",
			rooms_href:"http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/HEBB-100",
			rooms_seats:375,
			rooms_lat:49.2661,
			rooms_lon:-123.25165}]
};

const allRoomsQuery = {
	input: {
		WHERE: {
		},
		OPTIONS: {
			COLUMNS: ["rooms_fullname", "rooms_shortname"],
			ORDER: {
				dir: "DOWN", keys: ["rooms_shortname"]
			}
		}
	},
	output: [{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Woodward (Instructional Resources Centre-IRC)", rooms_shortname:"WOOD"},
		{rooms_fullname:"Wesbrook", rooms_shortname:"WESB"},
		{rooms_fullname:"Wesbrook", rooms_shortname:"WESB"},
		{rooms_fullname:"The Leon and Thea Koerner University Centre", rooms_shortname:"UCLL"},
		{rooms_fullname:"The Leon and Thea Koerner University Centre", rooms_shortname:"UCLL"},
		{rooms_fullname:"The Leon and Thea Koerner University Centre", rooms_shortname:"UCLL"},
		{rooms_fullname:"The Leon and Thea Koerner University Centre", rooms_shortname:"UCLL"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"West Mall Swing Space", rooms_shortname:"SWNG"},
		{rooms_fullname:"Student Recreation Centre", rooms_shortname:"SRC"},
		{rooms_fullname:"Student Recreation Centre", rooms_shortname:"SRC"},
		{rooms_fullname:"Student Recreation Centre", rooms_shortname:"SRC"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"School of Population and Public Health", rooms_shortname:"SPPH"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Jack Bell Building for the School of Social Work", rooms_shortname:"SOWK"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Neville Scarfe", rooms_shortname:"SCRF"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Pharmaceutical Sciences Building", rooms_shortname:"PHRM"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Ponderosa Commons: Oak House", rooms_shortname:"PCOH"},
		{rooms_fullname:"Robert F. Osborne Centre", rooms_shortname:"OSBO"},
		{rooms_fullname:"Robert F. Osborne Centre", rooms_shortname:"OSBO"},
		{rooms_fullname:"Robert F. Osborne Centre", rooms_shortname:"OSBO"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"Orchard Commons", rooms_shortname:"ORCH"},
		{rooms_fullname:"War Memorial Gymnasium", rooms_shortname:"MGYM"},
		{rooms_fullname:"War Memorial Gymnasium", rooms_shortname:"MGYM"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacMillan", rooms_shortname:"MCML"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"MacLeod", rooms_shortname:"MCLD"},
		{rooms_fullname:"Mathematics Annex", rooms_shortname:"MATX"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Mathematics", rooms_shortname:"MATH"},
		{rooms_fullname:"Leonard S. Klinck (also known as CSCI)", rooms_shortname:"LSK"},
		{rooms_fullname:"Leonard S. Klinck (also known as CSCI)", rooms_shortname:"LSK"},
		{rooms_fullname:"Leonard S. Klinck (also known as CSCI)", rooms_shortname:"LSK"},
		{rooms_fullname:"Leonard S. Klinck (also known as CSCI)", rooms_shortname:"LSK"},
		{rooms_fullname:"Life Sciences Centre", rooms_shortname:"LSC"},
		{rooms_fullname:"Life Sciences Centre", rooms_shortname:"LSC"},
		{rooms_fullname:"Life Sciences Centre", rooms_shortname:"LSC"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Frederic Lasserre", rooms_shortname:"LASR"},
		{rooms_fullname:"Iona Building", rooms_shortname:"IONA"},
		{rooms_fullname:"Iona Building", rooms_shortname:"IONA"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Irving K Barber Learning Centre", rooms_shortname:"IBLC"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hennings", rooms_shortname:"HENN"},
		{rooms_fullname:"Hebb", rooms_shortname:"HEBB"},
		{rooms_fullname:"Hebb", rooms_shortname:"HEBB"},
		{rooms_fullname:"Hebb", rooms_shortname:"HEBB"},
		{rooms_fullname:"Hebb", rooms_shortname:"HEBB"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Geography", rooms_shortname:"GEOG"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Forest Sciences Centre", rooms_shortname:"FSC"},
		{rooms_fullname:"Friedman Building", rooms_shortname:"FRDM"},
		{rooms_fullname:"Frank Forward", rooms_shortname:"FORW"},
		{rooms_fullname:"Frank Forward", rooms_shortname:"FORW"},
		{rooms_fullname:"Frank Forward", rooms_shortname:"FORW"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Food, Nutrition and Health", rooms_shortname:"FNH"},
		{rooms_fullname:"Earth Sciences Building", rooms_shortname:"ESB"},
		{rooms_fullname:"Earth Sciences Building", rooms_shortname:"ESB"},
		{rooms_fullname:"Earth Sciences Building", rooms_shortname:"ESB"},
		{rooms_fullname:"Earth and Ocean Sciences - Main", rooms_shortname:"EOSM"},
		{rooms_fullname:"Hugh Dempster Pavilion", rooms_shortname:"DMP"},
		{rooms_fullname:"Hugh Dempster Pavilion", rooms_shortname:"DMP"},
		{rooms_fullname:"Hugh Dempster Pavilion", rooms_shortname:"DMP"},
		{rooms_fullname:"Hugh Dempster Pavilion", rooms_shortname:"DMP"},
		{rooms_fullname:"Hugh Dempster Pavilion", rooms_shortname:"DMP"},
		{rooms_fullname:"Centre for Interactive  Research on Sustainability", rooms_shortname:"CIRS"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemistry", rooms_shortname:"CHEM"},
		{rooms_fullname:"Chemical and Biological Engineering Building", rooms_shortname:"CHBE"},
		{rooms_fullname:"Chemical and Biological Engineering Building", rooms_shortname:"CHBE"},
		{rooms_fullname:"Chemical and Biological Engineering Building", rooms_shortname:"CHBE"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Civil and Mechanical Engineering", rooms_shortname:"CEME"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Buchanan", rooms_shortname:"BUCH"},
		{rooms_fullname:"Brock Hall Annex", rooms_shortname:"BRKX"},
		{rooms_fullname:"Brock Hall Annex", rooms_shortname:"BRKX"},
		{rooms_fullname:"Biological Sciences", rooms_shortname:"BIOL"},
		{rooms_fullname:"Biological Sciences", rooms_shortname:"BIOL"},
		{rooms_fullname:"Biological Sciences", rooms_shortname:"BIOL"},
		{rooms_fullname:"Biological Sciences", rooms_shortname:"BIOL"},
		{rooms_fullname:"Auditorium Annex", rooms_shortname:"AUDX"},
		{rooms_fullname:"Auditorium Annex", rooms_shortname:"AUDX"},
		{rooms_fullname:"Anthropology and Sociology", rooms_shortname:"ANSO"},
		{rooms_fullname:"Anthropology and Sociology", rooms_shortname:"ANSO"},
		{rooms_fullname:"Anthropology and Sociology", rooms_shortname:"ANSO"},
		{rooms_fullname:"Anthropology and Sociology", rooms_shortname:"ANSO"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Henry Angus", rooms_shortname:"ANGU"},
		{rooms_fullname:"Allard Hall (LAW)", rooms_shortname:"ALRD"},
		{rooms_fullname:"Allard Hall (LAW)", rooms_shortname:"ALRD"},
		{rooms_fullname:"Allard Hall (LAW)", rooms_shortname:"ALRD"},
		{rooms_fullname:"Allard Hall (LAW)", rooms_shortname:"ALRD"},
		{rooms_fullname:"Allard Hall (LAW)", rooms_shortname:"ALRD"},
		{rooms_fullname:"Aquatic Ecosystems Research Laboratory", rooms_shortname:"AERL"}]
};

const roomsMultiplOrderKeys = {
	input:{WHERE: {AND: [
		{IS: {rooms_furniture: "*Tables*"}},
		{GT: {rooms_seats: 200}}]
	},
	OPTIONS: {COLUMNS: [
		"rooms_fullname",
		"rooms_shortname",
		"rooms_furniture",
		"rooms_number",
		"rooms_seats",
		"rooms_lat"],
	ORDER: {dir: "DOWN", keys: ["rooms_seats", "rooms_shortname", "rooms_number"]}
	}},
	output:[{rooms_fullname:"Robert F. Osborne Centre",
		rooms_shortname:"OSBO",rooms_furniture:"Classroom-Movable Tables & Chairs",
		rooms_number:"A",rooms_seats:442,rooms_lat:49.26047},{rooms_fullname:"Hebb",
		rooms_shortname:"HEBB",rooms_furniture:"Classroom-Fixed Tables/Fixed Chairs",rooms_number:"100",
		rooms_seats:375,rooms_lat:49.2661},{rooms_fullname:"Life Sciences Centre",rooms_shortname:"LSC",
		rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",rooms_number:"1002",rooms_seats:350,
		rooms_lat:49.26236},{rooms_fullname:"Life Sciences Centre",rooms_shortname:"LSC",
		rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",
		rooms_number:"1001",rooms_seats:350,rooms_lat:49.26236},
	{rooms_fullname:"Student Recreation Centre",rooms_shortname:"SRC",
		rooms_furniture:"Classroom-Movable Tables & Chairs",rooms_number:"220C",
		rooms_seats:299,rooms_lat:49.2683},{rooms_fullname:"Student Recreation Centre",
		rooms_shortname:"SRC",rooms_furniture:"Classroom-Movable Tables & Chairs",rooms_number:"220B",
		rooms_seats:299,rooms_lat:49.2683},{rooms_fullname:"Student Recreation Centre",
		rooms_shortname:"SRC",rooms_furniture:"Classroom-Movable Tables & Chairs",
		rooms_number:"220A",rooms_seats:299,rooms_lat:49.2683},{rooms_fullname:"Henry Angus",
		rooms_shortname:"ANGU",rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",rooms_number:"098",
		rooms_seats:260,rooms_lat:49.26486},{rooms_fullname:"Pharmaceutical Sciences Building",
		rooms_shortname:"PHRM",rooms_furniture:"Classroom-Fixed Tables/Movable Chairs",
		rooms_number:"1101",
		rooms_seats:236,rooms_lat:49.26229},{rooms_fullname:"Leonard S. Klinck (also known as CSCI)",
		rooms_shortname:"LSK",rooms_furniture:"Classroom-Fixed Tables/Fixed Chairs",rooms_number:"200",
		rooms_seats:205,rooms_lat:49.26545}]
};

export {
	roomsQueryAllKeys,
	allRoomsQuery,
	roomsMultiplOrderKeys
};
